version: '3.8'

services:
  academia-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academia-Service
    ports:
      - "${PORT:-3003}:3003"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SSL=${DATABASE_SSL}
      - PORT=3003
    restart: unless-stopped
    networks:
      - microservicios-topicos

networks:
  microservicios-topicos:
    external: true